# This is a basic workflow to help you get started with Actions

name: CxFlow_Jira

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        #CxFlow Action
      - name: CxFlow Action
        # You may pin to the exact commit or the version.
        # uses: checkmarx-ts/checkmarx-cxflow-github-action@fe2a395cbbee31268470d92b6c53ebc483005f0f
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.3        
        with:          
          project: JavaVulnerableLab-GitHub-action-Resolver
          # Select an Application Name used by downstream bug tracker systems
          app: HelloWorld
          # GitHub API Token
          #github_token: ${{ secrets.GH_TOKEN }}
          # Vulnerability Scanners (sast, sca, ast, cxgo)
          #------ SAST ------
          #scanners: sast
          # Provide Checkmarx URL
          #checkmarx_url: ${{secrets.CHECKMARX_URL}}
          # Provide team
          #team: /CxServer/SP/
          # Provide Checkmarx Username
          #checkmarx_username: ${{secrets.CHECKMARX_USERNAME}}
          # Provide Checkmarx Password
          #checkmarx_password: ${{secrets.CHECKMARX_PASSWORD}}
          # Provide Checkmarx Client Secret
          #checkmarx_client_secret: ${{secrets.CHECKMARX_CLIENT_SECRET}}
          # Select a Checkmarx Project
          #project: HelloWorld-GitHub-action
          #------ SCA ------
          scanners: sca          
          sca_api_url: https://api-sca.checkmarx.net
          # Provide SCA APP URL
          sca_app_url: https://sca.checkmarx.net
          # Provide SCA Access Control URL
          sca_access_control_url: https://platform.checkmarx.net    
          # Provide SCA Tenant
          sca_tenant: ${{ secrets.CX_SCA_TENANT }}
          # Provide SCA Username
          sca_username: ${{ secrets.CX_SCA_USERNAME }}
          # Provide SCA Password
          sca_password: ${{ secrets.CX_SCA_PASSWORD }}          
          bug_tracker: JIRA          
          params: --sca.filter-severity=MEDIUM --sca.team=/CxServer/TesterTeam --sca.include-sources=false --config=cx.config --repo-name=JavaVulnerableLab --namespace=TaynaCT --branch=master --jira.url=${{secrets.JIRA_URL}} --jira.username=${{secrets.JIRA_USER}} --jira.token=${{secrets.JIRA_TOKEN}}
          #Logs parameters
          #--logging.level.com.checkmarx.flow.custom=debug --logging.level.com.checkmarx.flow.service=debug --logging.level.com.checkmarx.flow.utils=debug --logging.level.com.checkmarx.sdk.service=debug
          
          
